#!/usr/bin/env python3
"""
DocuForge AI Document Agent

This script provides an API for generating documents from user messages.
"""

import os
import json
import uvicorn
from typing import Dict, List, Optional, Any
from fastapi import FastAPI, HTTPException, Body
from pydantic import BaseModel
from docuforge import generate_pdf
from docuforge.core.models import DocumentData, Section

# Create FastAPI app
app = FastAPI(title="DocuForge AI Agent", description="AI document generation agent using DocuForge")

class DocumentRequest(BaseModel):
    """Request model for document generation"""
    title: str
    content: str
    include_table: bool = False
    table_data: Optional[List[List[str]]] = None
    include_list: bool = False
    list_items: Optional[List[str]] = None
    author: Optional[str] = "AI Agent User"

class DocumentResponse(BaseModel):
    """Response model with document information"""
    filename: str
    size_kb: float
    message: str

def process_content(content: str) -> List[Section]:
    """Process user content into document sections"""
    sections = []
    
    # Split content into paragraphs
    paragraphs = content.split("\n\n")
    for paragraph in paragraphs:
        if paragraph.strip():
            sections.append(Section(type="paragraph", text=paragraph))
    
    return sections

@app.post("/generate-document", response_model=DocumentResponse)
async def generate_document(request: DocumentRequest = Body(...)):
    """Generate a document based on user input"""
    try:
        # Start with content sections
        sections = process_content(request.content)
        
        # Add list if requested
        if request.include_list and request.list_items:
            sections.append(Section(type="paragraph", text="\nKey Points:"))
            sections.append(Section(type="list", items=request.list_items))
            
        # Add table if requested
        if request.include_table and request.table_data:
            sections.append(Section(type="paragraph", text="\nData Table:"))
            sections.append(Section(type="table", rows=request.table_data))
            
        # Add footer with author
        sections.append(Section(
            type="footer", 
            text=f"Generated by DocuForge v0.1.0 for {request.author} | Page {{page_number}} of {{total_pages}}"
        ))
        
        # Create document
        doc = DocumentData(
            title=request.title,
            sections=sections
        )
        
        # Generate PDF
        pdf_bytes = generate_pdf(doc)
        
        # Save to file
        filename = f"{request.title.replace(' ', '_')}.pdf"
        with open(filename, "wb") as f:
            f.write(pdf_bytes)
        
        # Return response
        size_kb = len(pdf_bytes) / 1024
        return DocumentResponse(
            filename=filename,
            size_kb=round(size_kb, 2),
            message=f"Document successfully generated! Size: {round(size_kb, 2)} KB"
        )
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating document: {str(e)}")

@app.get("/")
async def root():
    """Welcome message"""
    return {
        "message": "Welcome to DocuForge AI Document Agent",
        "usage": "Send a POST request to /generate-document with title and content"
    }

def main():
    """Run the API server"""
    print("Starting DocuForge AI Document Agent...")
    print("API Documentation available at http://localhost:8000/docs")
    uvicorn.run(app, host="0.0.0.0", port=8000)

# CLI interface for testing
if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="DocuForge AI Document Agent")
    parser.add_argument("--cli", action="store_true", help="Run in CLI mode instead of API server")
    args = parser.parse_args()
    
    if args.cli:
        print("DocuForge AI Document Generator (CLI Mode)")
        
        title = input("Document title: ")
        print("Enter content (press Enter twice when done):")
        
        content_lines = []
        while True:
            line = input()
            if not line and content_lines and not content_lines[-1]:
                break
            content_lines.append(line)
        
        content = "\n".join(content_lines)
        
        include_list = input("Include a bullet list? (y/n): ").lower() == 'y'
        list_items = []
        if include_list:
            print("Enter list items (one per line, empty line to finish):")
            while True:
                item = input("- ")
                if not item:
                    break
                list_items.append(item)
        
        include_table = input("Include a table? (y/n): ").lower() == 'y'
        table_data = []
        if include_table:
            print("Enter table header (comma separated values):")
            header = input().split(",")
            table_data.append([h.strip() for h in header])
            
            print("Enter table rows (comma separated values, empty line to finish):")
            while True:
                row = input()
                if not row:
                    break
                table_data.append([cell.strip() for cell in row.split(",")])
        
        author = input("Author name (press Enter for default): ")
        
        request = DocumentRequest(
            title=title,
            content=content,
            include_list=include_list,
            list_items=list_items if include_list else None,
            include_table=include_table,
            table_data=table_data if include_table else None,
            author=author if author else "AI Agent User"
        )
        
        # Create document
        try:
            sections = process_content(request.content)
            
            if request.include_list and request.list_items:
                sections.append(Section(type="paragraph", text="\nKey Points:"))
                sections.append(Section(type="list", items=request.list_items))
                
            if request.include_table and request.table_data:
                sections.append(Section(type="paragraph", text="\nData Table:"))
                sections.append(Section(type="table", rows=request.table_data))
                
            sections.append(Section(
                type="footer", 
                text=f"Generated by DocuForge v0.1.0 for {request.author} | Page {{page_number}} of {{total_pages}}"
            ))
            
            doc = DocumentData(
                title=request.title,
                sections=sections
            )
            
            # Generate PDF
            print("Generating PDF...")
            pdf_bytes = generate_pdf(doc)
            
            # Save to file
            filename = f"{request.title.replace(' ', '_')}.pdf"
            with open(filename, "wb") as f:
                f.write(pdf_bytes)
            
            size_kb = len(pdf_bytes) / 1024
            print(f"Document successfully generated and saved as {filename}")
            print(f"PDF size: {round(size_kb, 2)} KB")
            
        except Exception as e:
            print(f"Error: {str(e)}")
    else:
        main()
